In [20]:
# 1. How to import pandas and check the version?
import pandas as pd 
print(pd.__version__)
print(pd.show_versions(as_json=True))

0.24.2
{'system': {'commit': None, 'python': '3.7.3.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'None.None'}, 'dependencies': {'pandas': '0.24.2', 'pytest': '4.5.0', 'pip': '19.1.1', 'setuptools': '41.0.1', 'Cython': '0.29.11', 'numpy': '1.16.4', 'scipy': '1.2.1', 'pyarrow': None, 'xarray': None, 'IPython': '7.6.0', 'sphinx': '2.1.2', 'patsy': '0.5.1', 'dateutil': '2.8.0', 'pytz': '2019.1', 'blosc': None, 'bottleneck': '1.2.1', 'tables': '3.5.1', 'numexpr': '2.6.9', 'feather': None, 'matplotlib': '3.0.3', 'openpyxl': '2.6.2', 'xlrd': '1.2.0', 'xlwt': '1.3.0', 'xlsxwriter': '1.1.8', 'lxml.etree': '4.3.4', 'bs4': '4.6.3', 'html5lib': '1.0.1', 'sqlalchemy': '1.3.5', 'pymysql': None, 'psycopg2': '2.7.6.1 (dt dec pq3 ext lo64)', 'jinja2': '2.10.1', 's3fs': None, 'fastparquet': None, 'pandas_gbq': None, 'pandas_datar

In [10]:
# 2. How to create a series from a list, numpy array and dict?
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
print(ser1.head())
print("-------------------")
ser2 = pd.Series(myarr)
print(ser2.head())
print("-------------------")
ser3 = pd.Series(mydict)
print(ser3.head())


0    a
1    b
2    c
3    e
4    d
dtype: object
-------------------
0    0
1    1
2    2
3    3
4    4
dtype: int32
-------------------
a    0
b    1
c    2
e    3
d    4
dtype: int64


In [15]:
# 3. How to convert the index of a series into a column of a dataframe?
df = ser3.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [17]:
# 4. How to combine many series to form a dataframe?
df = pd.concat([ser1,ser2], axis=1)
print(df.head())

df1 = pd.DataFrame({'col1':ser1, 'col2':ser2, 'col3':ser3})
print(df1.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4
  col1  col2  col3
0    a   0.0   NaN
1    b   1.0   NaN
2    c   2.0   NaN
3    e   3.0   NaN
4    d   4.0   NaN


In [18]:
# 5. How to assign name to the series’ index? Give a name to the series ser calling it ‘alphabets’.
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'aplhabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: aplhabets, dtype: object

In [26]:
# 6. How to get the items of series A not present in series B? From ser1 remove items present in ser2.
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [42]:
# 7. How to get the items not common to both series A and series B? Get all items of ser1 and ser2 not common to both.
ser3 = ser1[~ser1.isin(ser2)].append(ser2[~ser2.isin(ser1)])
print(ser3)

# Alternate method
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


In [45]:
# 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))
print(ser.describe())
print("-------------------------")
# Alternate Method
# Solution
print(np.percentile(ser, q=[0, 25, 50, 75, 100]))

count    25.000000
mean      9.990302
std       4.481111
min      -0.027421
25%       6.941619
50%       9.353893
75%      13.338169
max      18.845407
dtype: float64
-------------------------
[-0.02742067  6.94161875  9.35389326 13.33816926 18.84540741]


In [47]:
# 9. How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

f    6
b    5
g    5
c    4
d    4
h    4
e    2
dtype: int64

In [65]:
# 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’? 
# From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.
rn = np.random.RandomState(100)
ser = pd.Series(rn.randint(1, 5, [12]))
print(ser)
print(ser.value_counts())
ser.where(ser.isin(ser[ser.value_counts().index[:2]]), 'Other')

0     1
1     1
2     4
3     4
4     4
5     4
6     1
7     3
8     3
9     1
10    3
11    2
dtype: int32
4    4
1    4
3    3
2    1
dtype: int64


0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object

In [71]:
# 11. How to bin a numeric series to 10 groups of equal size?
# Bin the series ser into 10 equal deciles and replace the values with the bin name.
ser = pd.Series(np.random.random(20))
print(pd.qcut(ser,10,["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]).head())

0      Ten
1     Five
2      Ten
3    Eight
4     Four
dtype: category
Categories (10, object): [One < Two < Three < Four ... Seven < Eight < Nine < Ten]


In [74]:
# 12. How to convert a numpy array to a dataframe of given shape? 
# Reshape the series ser into a dataframe with 7 rows and 5 columns
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7,5))
df.head()

0  1  2  3  4
0  1  1  2  5  1
1  6  8  8  9  5
2  5  3  1  7  6
3  8  7  1  6  5
4  6  2  3  1  2

In [88]:
# 13. How to find the positions of numbers that are multiples of 3 from a series?
# Find the positions of numbers that are multiples of 3 from ser.
ser = pd.Series([10,11,2,32,4,51,6,70,8,9])
np.argwhere(ser % 3 == 0)

array([[5],
       [6],
       [9]], dtype=int64)

In [91]:
# 14. How to extract items at given positions from a series
# From ser, extract the items at positions in list pos.
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [95]:
# 15. How to stack two series vertically and horizontally ?
# Stack ser1 and ser2 vertically and horizontally (to form a dataframe).
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
#print(np.vstack((ser1,ser2)))
#print(np.hstack((ser1,ser2)))
#ser1.append(ser2)
df = pd.concat([ser1, ser2], axis=1)
df.head()

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [102]:
# 16. How to get the positions of items of series A in another series B? Get the positions of items of ser2 in ser1 as a list.
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [105]:
# 17. How to compute the mean squared error on a truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
print(np.mean(truth))
print(np.mean(pred))
np.mean((truth - pred)**2)

4.5
4.965610969412051


0.2708059691387452

In [107]:
# 18. How to convert the first character of each element in a series to uppercase?
# Change the first character of each word to upper case in each word of ser.
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Sol 1
ser.map(lambda x: x.title())

# Sol 2
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [110]:
# 19. How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [112]:
# 20. How to compute difference of differences between consequtive numbers of a series?
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
ser.diff().diff()

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [115]:
# 21. How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
#ser.map(lambda x: parse(x))

# SOlution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [123]:
# 22. How to get the day of month, week number, day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
# Solution 1
from dateutil.parser import parse
ser_ts  = ser.map(lambda x: parse(x))
# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.weekday_name.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [125]:
# 23. How to convert year-month string to dates corresponding to the 4th day of the month?
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))
# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
#[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [131]:
# 24. How to filter words that contain atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
mask
#ser[mask]

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [136]:
# 25. How to filter valid emails from a series?
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

# Solution 1
import re
mask = emails.map(lambda x: bool(re.match(pattern, x)))
#emails[mask]

# Solution 2
emails.str.findall(pattern, flags= re.IGNORECASE)


0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [146]:
# 26. How to get the mean of a series grouped by another series?
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
#import numpy as np
#df = pd.DataFrame(np.array(fruit, weights), columns=['fruits', 'weights'], dtype=np.object)

weights.groupby(fruit).mean()


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['apple', 'apple', 'carrot', 'banana', 'carrot', 'apple', 'apple', 'banana', 'apple', 'banana']


apple     5.000000
banana    7.333333
carrot    4.000000
dtype: float64

In [147]:
# 27. How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
np.sqrt(sum((q-p)**2))

18.16590212458495

In [148]:
# 28. How to find all the local maxima (or peaks) in a numeric series?
# Get the positions of peaks (values surrounded by smaller values on both sides) in ser.
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

In [158]:
# 29. How to replace missing spaces in a string with the least frequent character?
my_str = 'dbc deb abed gade'
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
#freq
least_freq = freq.dropna().index[-1]
least_freq
"".join(ser.replace(' ', least_freq))

'dbcgdebgabedggade'

In [170]:
# 30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

print(pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT')))

2000-01-01    4
2000-01-08    1
2000-01-15    4
2000-01-22    2
2000-01-29    1
2000-02-05    2
2000-02-12    8
2000-02-19    1
2000-02-26    5
2000-03-04    3
Freq: W-SAT, dtype: int32


In [172]:
# 31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [174]:
# 32. How to compute the autocorrelations of a numeric series?
# Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.77, 0.81, 0.68, 0.72, 0.64, 0.65, 0.2, 0.31, 0.16, 0.25]
Lag having highest correlation:  2


In [176]:
# 33. How to import only every nth row from a csv file to create a dataframe?

# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

    
# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()

# Solution 3: Use csv reader
#import csv          
#with open('BostonHousing.csv', 'r') as f:
#    reader = csv.reader(f)
#    out = []
#    for i, row in enumerate(reader):
#        if i%50 == 0:
#            out.append(row)

#df2 = pd.DataFrame(out[1:], columns=out[0])
print(df2.head())

        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
